### ISSUE TITLE
Question: Use of `When`

### ISSUE THREAD

**Issue by pwrnrd** [node-ts/ddd#9]
Great package! I especially like the way how events are handled. However, one thing caught my eye. 
Within an aggregate events are published. This makes perfect sense as per DDD your not allowed to update different aggregates in the same transaction. To achieve eventual consistencies, events published in one aggregate can be used by services to update other aggregates. However, in this library the aggregate which publishes events also handles its own events (through `when()` on the abstract aggregate root). I was wondering why this is? Why not simple call a method on the aggregate?

**Comment by dropdevcoding** [comment]
I only recently stumbled upon that set of so far good looking libraries and I also want to state that I don't know what the authors' intention is here but I've seen this pattern in the context of event sourcing several times. Imagine you have an event stream and you want to reconstitute your aggregate root out of a set of events. In order to do that you need a clean separation of action and effect inside the aggregate root (command -> event) so the aggregate root may be reconstituted only by applying the events that happened and this is what the `when` prefixed methods are for. 

Triggering the application of the event to the aggregate root through `when()` also might increment the version of the aggregate root whenever an event has been applied. That is useful if you

a) do event sourcing for the order of the events to be applied 
b) don't do event sourcing and you'd like to have optimistic concurrency control

Hope that might help you a bit. Happy to discuss / enhance

**Comment by pwrnrd** [comment]
Ah I see, that is interesting. I think this is a good approach to reconstructing the aggregate from events. Thanks!
